# Generated by Django 4.1.3 on 2022-11-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='color',
            field=models.CharField(blank=True, default='#3A86FF', max_length=7),
        ),
    ]
