# Generated by Django 4.1.3 on 2022-11-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_challenge_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='color',
            field=models.CharField(blank=True, choices=[('#ffbe0b', 'Amber'), ('#fb5607', 'Orange Pantone'), ('#FF006E', 'Winter Sky'), ('#8338EC', 'Blue Violet'), ('#3A86FF', 'Azure')], default='#3A86FF', max_length=7),
        ),
    ]
