# Generated by Django 4.1.3 on 2022-12-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('sender', 'receiver')},
        ),
    ]
