# Generated by Django 4.1.3 on 2022-12-02 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_relationship_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=8)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_challenge', to='main.challenge')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_receiver', to='main.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_sender', to='main.profile')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
